"""empty message

Revision ID: 703011b330d8
Revises: cac6a6560833
Create Date: 2018-09-17 03:39:46.431838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703011b330d8'
down_revision = 'cac6a6560833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('anime', 'title_alt',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'title_alt',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('anime', 'title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
